# Generated by Django 6.1 on 2026-08-24 11:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=32, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('light_agent', 'Light Agent')], default='agent', max_length=20)),
                ('password_hash', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agents',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=32, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('segment', models.CharField(choices=[('standard', 'Standard'), ('vip', 'Vip')], default='standard', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, choices=[('billing', 'Billing'), ('technical', 'Technical'), ('onboarding', 'Onboarding'), ('general', 'General')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_groups', to='accounts.agent')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='GroupAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_agents', to='accounts.agent')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_agents', to='accounts.group')),
            ],
            options={
                'db_table': 'group_agents',
                'constraints': [models.UniqueConstraint(fields=('group', 'agent'), name='uq_group_agents_group_agent')],
            },
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('agent_login_verification', 'Agent Login Verification'), ('customer_login', 'Customer Login')], max_length=40)),
                ('code_hash', models.CharField(max_length=64)),
                ('attempts', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='accounts.agent')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='accounts.customer')),
            ],
            options={
                'db_table': 'otp_codes',
                'indexes': [models.Index(fields=['agent'], name='otp_codes_agent_i_9455ec_idx'), models.Index(fields=['customer'], name='otp_codes_custome_757be0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('agent__isnull', False), ('customer__isnull', True)), models.Q(('agent__isnull', True), ('customer__isnull', False)), _connector='OR'), name='otp_codes_exactly_one_subject')],
            },
        ),
    ]
