# Generated by Django 6.1 on 2026-08-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('agent_login_verification', 'Agent Login Verification'), ('customer_login', 'Customer Login'), ('customer_ticket_submission', 'Customer Ticket Submission')], max_length=40),
        ),
    ]
