# Generated by Django 6.1 on 2026-08-24 11:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('on_ticket_created', 'On Ticket Created'), ('scheduled', 'Scheduled')], max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('rule_order', models.IntegerField(default=0)),
                ('schedule_interval_minutes', models.IntegerField(blank=True, null=True)),
                ('conditions', models.JSONField(default=list)),
                ('actions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'automation_rules',
                'indexes': [models.Index(fields=['rule_type', 'active'], name='automation__rule_ty_deb9ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='CannedResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canned_responses', to='accounts.agent')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canned_responses', to='accounts.group')),
            ],
            options={
                'db_table': 'canned_responses',
            },
        ),
    ]
