# Generated by Django 6.1 on 2026-09-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_faq_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('bad', 'Bad')], max_length=4, null=True),
        ),
    ]
