# Generated by Django 6.1 on 2026-09-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        # Data cleanup, not a schema change: existing rows hold the previous
        # pass's binary 'good'/'bad' text, which can't cast to a float
        # column and has no principled 1-5 mapping the PRD specifies. These
        # were dev-test submissions, not real data — clearing them (and the
        # submission timestamp, so the review is testable again under the
        # new flow) is correct here; a real migration with production data
        # would need a product decision on how to map old scores forward.
        migrations.RunSQL(
            "UPDATE reviews SET score = NULL, submitted_at = NULL WHERE score IN ('good', 'bad')",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
